#!/bin/bash
#SBATCH --nodes=1                  # Number of requested nodes
#SBATCH --ntasks=45                # Cores per node requested
#SBATCH --time=7-50:00:00        	# Timelimit
#SBATCH --mem=300gb                # Job memory (1024gb=1tb)
#SBATCH --mail-type=BEGIN,END,FAIL         
#SBATCH --mail-user=jrodram@colostate.edu
#SBATCH --partition=wrighton-hi

cd /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/

/home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/_viral_pipeline_erpe_pore_scripts/virsorter2_B/virsorter2_CheckV_rerunVirSorter2_multiple_assembly_B.sh /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/_test_list_assembly_F.txt

/home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/_viral_pipeline_erpe_pore_scripts/virsorter2_B/viral_10kb_multiple_sample_cluster_B.sh /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/_test_list_assembly_F.txt

/home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/_viral_pipeline_erpe_pore_scripts/virsorter2_B/viral_10kb_individual_sample_cluster_B.sh /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/_test_list_assembly_F.txt

mkdir cluster_genomes_results_virsorter2_B
mv VirSorter2_allsamples_clustered_together_B cluster_genomes_results_virsorter2_B
mv individually_clustered_B cluster_genomes_results_virsorter2_B

echo "I have finished the viral pipeliner successfully."



############Individual Sample Cluster
#!/bin/bash
cd /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/
mkdir individually_clustered_B
cd /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/individually_clustered_B

for element in $(<$1)
do
mkdir "$element"_clustergenomes_files_B
cp /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/VirSorter2_allsamples_clustered_together_B/"$element"_B_final-viral-combined.fa /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/individually_clustered_B
Cluster_genomes_5.1.pl -f /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/individually_clustered_B/"$element"_B_final-viral-combined.fa -c 85 -i 95 -t 6
mv "$element"_B_final-viral-combined_95-85.fna "$element"_clustergenomes_files_B
mv "$element"_B_final-viral-combined_95-85.clstr "$element"_clustergenomes_files_B
mv "$element"_B_final-viral-combined-cover.csv "$element"_clustergenomes_files_B
mv "$element"_B_final-viral-combined.fasta "$element"_clustergenomes_files_B
mv "$element"_B_final-viral-combined-nucmer.out.coords "$element"_clustergenomes_files_B
mv "$element"_B_final-viral-combined-nucmer.out.coords.sorted "$element"_clustergenomes_files_B
mv "$element"_B_final-viral-combined-nucmer.out.delta "$element"_clustergenomes_files_B
done
echo "finished individual sample clustering with no errors"
exit 0

###########Multiple sample cluster
#!/bin/bash
#$1 list of fasta files that will be clustered in multiples.

cd /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/
mkdir VirSorter2_allsamples_clustered_together_B

for element in $(<$1)
do
cp /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/"$element"_B.virsorter2out/vs2-pass2/final-viral-combined.fa /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/VirSorter2_allsamples_clustered_together_B/
mv /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/VirSorter2_allsamples_clustered_together_B/final-viral-combined.fa /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/VirSorter2_allsamples_clustered_together_B/"$element"_B_final-viral-combined.fa
done
echo "I copied all the files succesfully. Starting clustering."

cd VirSorter2_allsamples_clustered_together_B
cat *.fa > all_samples_ge10kb_viruses_B.fasta
mkdir cluster_genomes_multi_sample_out_B
Cluster_genomes_5.1.pl -f all_samples_ge10kb_viruses_B.fasta -c 85 -i 95 -t 6
mv all_samples_ge10kb_viruses_B_95-85.fna cluster_genomes_multi_sample_out_B
mv all_samples_ge10kb_viruses_B_95-85.clstr cluster_genomes_multi_sample_out_B
mv all_samples_ge10kb_viruses_B-cover.csv cluster_genomes_multi_sample_out_B
mv all_samples_ge10kb_viruses_B.fasta cluster_genomes_multi_sample_out_B
mv all_samples_ge10kb_viruses_B-nucmer.out.coords cluster_genomes_multi_sample_out_B
mv all_samples_ge10kb_viruses_B-nucmer.out.coords.sorted cluster_genomes_multi_sample_out_B
mv all_samples_ge10kb_viruses_B-nucmer.out.delta cluster_genomes_multi_sample_out_B

echo "I finished multi sample clustering with no errors"
exit 0

###########VirSorter2, checkv and virsorter2 2nd run
#!/bin/bash

#$1 list of directories that contain assemblies.

source /opt/Miniconda2/miniconda2/bin/activate virsorter2
cd /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/

for element in $(<$1)
do
mkdir "$element"_B.virsorter2out
cd "$element"_B.virsorter2out
virsorter run -w vs2_"$element"_pass1 --keep-original-seq -i ../"$element"_B/"$element"_B.contigs.fa -w vs2-pass1 --include-groups dsDNAphage,ssDNA --min-length 10000 --min-score 0.5 -j 45 all
checkv contamination /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/"$element"_B.virsorter2out/vs2-pass1/final-viral-combined.fa checkv_out
checkv completeness /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/"$element"_B.virsorter2out/vs2-pass1/final-viral-combined.fa checkv_out
checkv repeats /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/"$element"_B.virsorter2out/vs2-pass1/final-viral-combined.fa checkv_out
checkv quality_summary /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/pore_water/"$element"_B.virsorter2out/vs2-pass1/final-viral-combined.fa checkv_out
virsorter run --seqname-suffix-off --viral-gene-enrich-off --prep-for-dramv -i checkv_out/cleaned_contigs.fna -w vs2-pass2 --include-groups dsDNAphage,ssDNA --min-length 10000 --min-score 0.5 -j 45 all
cd ../
done
echo "VirSorter2 and checkV are complete"
