#!/bin/bash
#SBATCH --nodes=1                  # Number of requested nodes
#SBATCH --ntasks=20                # Cores per node requested
#SBATCH --time=7-1:00:00        	# Timelimit
#SBATCH --mem=150gb                # Job memory (1024gb=1tb)
#SBATCH --mail-type=BEGIN,END,FAIL         
#SBATCH --mail-user=jrodram@colostate.edu
#SBATCH --partition=wrighton-hi

cd /home/projects-wrighton-2/GROWdb/WHONDRS_2018/metaG/2018_rivers/erpe/erpe_JRR/surface_and_pore_viral_db_analyses/virhostmatcher/Oct282021

python /opt/VirHostMatcher/vhm.py -v virus -b host -o output
