#!/bin/bash

#$1 list of names of the assemblies.

#####metaSPAdes BBCMS

for element in $(<$1)
do
cd "$element"_filter
bbcms.sh mincount=2 highcountfraction=0.6 in="$element"_interleaved.anqdpht.fastq.gz out="$element"_bbcms.fastq.gz

spades.py -o "$element"_metaspades_assembly --only-assembler -k 33,55,77,99,127 --meta -t 25 --12 "$element"_bbcms.fastq.gz
cd ..
done
echo "metaSPAdes pipeline seems to have run all the way through"


##########megahit

for element in $(<$1)
do
megahit -1 trimmed_"$element"_R1_001.fastq -2 trimmed_"$element"_R2_001.fastq --k-min 31 --k-max 121 --k-step 10 -m 0.4 -t 30 --out-prefix "$element" -o "$element"_megahit
done
echo "megahit seems to have run all the way through"

###########IDBA-UD

for element in $(<$1)
do
mkdir "$element"_F
cd "$element"_F
idba_ud -r /home/projects/WHONDRS/metaG/2018_rivers/erpe/erpe_JRR/surface_water/trimmed_25_pcnt_subassembly_reads/trimmed_"$element"_R1R2_ALL_trimmed_25pcnt.fa -o "$element"idba_assembled_output_25pcnt --num_threads 30
cd ..
done
echo "25% with IDBA UD seems to have run all the way through"
